import type { APIRoute } from 'astro';
import { SITE, INDEX_THRESHOLDS } from '../config/site.config';
import { CATEGORIES } from '../config/categories';
import { AUTHORS } from '../config/authors';
import {
  getPublishedArticles,
  getAllTags,
  getArticlesByCategory,
  getArticlesByAuthor,
  getArticlesByTag,
  slugOf,
} from '../lib/articles';

/**
 * Canonical sitemap at /sitemap.xml.
 *
 * Hand-built rather than generated by @astrojs/sitemap for three reasons:
 *   1. A single clean URL — no sitemap-index indirection for a site this size.
 *      One sitemap file legitimately holds up to 50,000 URLs.
 *   2. Real `lastmod` values taken from each article's updatedDate/publishDate,
 *      and for archives the newest article they contain. The generated version
 *      stamped every URL with the build time, which tells crawlers nothing and
 *      trains them to ignore the field.
 *   3. Paginated pages (/articles/2/ etc.) are excluded. They are served
 *      noindex,follow, and listing a noindex URL in a sitemap is a
 *      contradictory signal.
 *
 * WHEN ADDING A NEW ROUTE TYPE, add it here — this list is explicit by design,
 * so a new page type is a deliberate inclusion rather than an accident.
 */

export const prerender = true;

interface Entry {
  loc: string;
  lastmod?: Date;
  changefreq:
    | 'always'
    | 'hourly'
    | 'daily'
    | 'weekly'
    | 'monthly'
    | 'yearly'
    | 'never';
  priority: number;
}

/** XML-escape — cheap insurance even though our slugs are kebab-case. */
const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
   .replace(/"/g, '&quot;').replace(/'/g, '&apos;');

const url = (path: string) => new URL(path, SITE.url).toString();

/** Newest publish/update date in a set of articles. */
function newest(articles: { data: { publishDate: Date; updatedDate?: Date } }[]) {
  if (!articles.length) return undefined;
  return articles
    .map((a) => a.data.updatedDate ?? a.data.publishDate)
    .reduce((a, b) => (a > b ? a : b));
}

export const GET: APIRoute = async () => {
  const articles = await getPublishedArticles();
  const tags = await getAllTags();
  const latest = newest(articles);

  const entries: Entry[] = [];

  // ---------- Home ----------
  entries.push({ loc: url('/'), lastmod: latest, changefreq: 'daily', priority: 1.0 });

  // ---------- Section hubs ----------
  for (const path of ['/articles/', '/news/', '/guides/', '/reviews/']) {
    entries.push({ loc: url(path), lastmod: latest, changefreq: 'daily', priority: 0.9 });
  }
  entries.push({
    loc: url('/categories/'),
    lastmod: latest,
    changefreq: 'weekly',
    priority: 0.8,
  });

  // ---------- Articles ----------
  for (const article of articles) {
    entries.push({
      loc: url(`/articles/${slugOf(article)}/`),
      lastmod: article.data.updatedDate ?? article.data.publishDate,
      changefreq: 'monthly',
      priority: article.data.featured ? 0.9 : 0.8,
    });
  }

  // ---------- Category archives ----------
  // Only categories at or above the indexing threshold. Thin archives are
  // served noindex,follow, and listing a noindex URL in a sitemap is a
  // contradictory signal — the two must agree.
  for (const category of CATEGORIES) {
    const inCategory = await getArticlesByCategory(category.slug);
    if (inCategory.length < INDEX_THRESHOLDS.category) continue;
    entries.push({
      loc: url(`/category/${category.slug}/`),
      lastmod: newest(inCategory),
      changefreq: 'weekly',
      priority: 0.7,
    });
  }

  // ---------- Author archives ----------
  // The /authors/ hub answers "who is responsible for this content" — a page
  // both readers and quality raters look for, so it belongs in the sitemap.
  entries.push({
    loc: url('/authors/'),
    lastmod: latest,
    changefreq: 'monthly',
    priority: 0.6,
  });

  for (const author of AUTHORS) {
    const byAuthor = await getArticlesByAuthor(author.slug);
    if (!byAuthor.length) continue;
    entries.push({
      loc: url(`/authors/${author.slug}/`),
      lastmod: newest(byAuthor),
      changefreq: 'weekly',
      priority: 0.6,
    });
  }

  // ---------- Tag archives ----------
  // Same threshold rule as categories. At current volume most tags match a
  // single article, so this excludes the majority by design.
  for (const { tag } of tags) {
    const tagged = await getArticlesByTag(tag);
    if (tagged.length < INDEX_THRESHOLDS.tag) continue;
    entries.push({
      loc: url(`/tag/${tag}/`),
      lastmod: newest(tagged),
      changefreq: 'weekly',
      priority: 0.5,
    });
  }

  // ---------- Static pages ----------
  entries.push(
    { loc: url('/about/'), changefreq: 'monthly', priority: 0.6 },
    { loc: url('/contact/'), changefreq: 'monthly', priority: 0.6 },
    { loc: url('/editorial-policy/'), changefreq: 'yearly', priority: 0.4 },
    { loc: url('/privacy-policy/'), changefreq: 'yearly', priority: 0.3 },
    { loc: url('/terms/'), changefreq: 'yearly', priority: 0.3 },
    { loc: url('/cookie-policy/'), changefreq: 'yearly', priority: 0.3 },
    { loc: url('/disclaimer/'), changefreq: 'yearly', priority: 0.3 }
  );

  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries
  .map(
    (e) => `  <url>
    <loc>${esc(e.loc)}</loc>${
      e.lastmod ? `\n    <lastmod>${e.lastmod.toISOString().split('T')[0]}</lastmod>` : ''
    }
    <changefreq>${e.changefreq}</changefreq>
    <priority>${e.priority.toFixed(1)}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`;

  return new Response(body, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
};
